<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 2.1.2 on 2018-12-14 10:56
=======
# Generated by Django 2.1.3 on 2018-12-13 20:37
>>>>>>> d8dfb3b82b0a3c399facec175589ef5665ded571
=======
# Generated by Django 2.1.3 on 2018-12-13 20:37
>>>>>>> d8dfb3b82b0a3c399facec175589ef5665ded571

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='flag',
        ),
    ]
