# Generated by Django 2.1.3 on 2018-12-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_received', to='matchapp.Member')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_sent', to='matchapp.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', through='matchapp.Like', to='matchapp.Member'),
        ),
    ]
