<<<<<<< HEAD
# Generated by Django 2.1.2 on 2018-12-15 13:48
=======
# Generated by Django 2.1.2 on 2018-12-15 13:46
>>>>>>> 647ee4f4e7c157faed7d13392ed290ee0c49968b

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
