# Generated by Django 2.1.3 on 2018-12-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='matchapp.Member')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='matchapp.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='numbers',
            field=models.ManyToManyField(related_name='related_nums', through='matchapp.Number', to='matchapp.Member'),
        ),
    ]
