# Generated by Django 2.1.3 on 2018-12-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='flag',
        ),
    ]
