# Generated by Django 2.1.3 on 2018-12-11 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0002_auto_20181211_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. only 11 digits allowed.", regex='^\\+?1?\\d{11}$')]),
        ),
    ]
