# Generated by Django 2.1.2 on 2018-12-20 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0002_auto_20181216_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. only 11 digits allowed.", regex='^(?:0|\\+?44)(?:\\d\\s?){9,11}$')]),
        ),
    ]
