# Generated by Django 2.1.3 on 2018-12-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0002_auto_20181214_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_member_friends_+', to='matchapp.Member'),
        ),
    ]
